// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/layout/Aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Father: typeof import('./src/components/FatherSon/Father.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/home/index.vue')['default']
    IconMenu: typeof import('~icons/ic/on-menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Son: typeof import('./src/components/FatherSon/Son.vue')['default']
    Undefined: typeof import('./src/layout/index.vue')['default']
  }
}
