// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Father: typeof import('./src/components/FatherSon/Father.vue')['default']
    FatherSlot: typeof import('./src/components/Slot/FatherSlot.vue')['default']
    Header: typeof import('./src/layout/Header.vue')['default']
    Home: typeof import('./src/components/Home/index.vue')['default']
    MouseTracker: typeof import('./src/components/Slot/MouseTracker.vue')['default']
    MyImg: typeof import('./src/hooks/MyImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowImages: typeof import('./src/components/ShowImages/index.vue')['default']
    Son: typeof import('./src/components/FatherSon/Son.vue')['default']
    SonSlot: typeof import('./src/components/Slot/SonSlot.vue')['default']
    Undefined: typeof import('./src/layout/index.vue')['default']
    WangEdit: typeof import('./src/components/WangEdit/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
  }
}
